### ISSUE TITLE
Question about if 

### ISSUE THREAD

**Issue by anonymousResearch12** [najoungkim/pdtb3#11]
The pdtb3_make_splits_xval function in ./preprocess [preprocess_pdtb3.py seems to confuse the cases of random split and cross validation in the code. Could you verify if this is correct?

**Comment by najoungkim** [comment]
Thanks! Could you elaborate? To me it seems that if `random_sections` is True, you go to the else statement and get randomly shuffled section ordering (for xval). If it is False, you go to the first if and get a fixed section ordering (for xval) every time, starting from the case where dev has sections 0 & 1.

Let me know if you think otherwise!

**Comment by anonymousResearch12** [comment]
Thank you for the reply. My understanding is that the default value for random_sections is False, so if not random_selection, it means true, you go to the if part, and the else part means random_selection is false. (???)

**Comment by najoungkim** [comment]
Yes, because the default is `random_sections=False` the default behavior is following the first if. The else part is followed when random_sections is True, not False.

You can read the if/else in the code as:

```
if not random_sections: 
   fixed split
elif random_sections:
   random split
```

does this make sense?

**Comment by anonymousResearch12** [comment]
Ah, I see. Thank you very much for the clarification.
